### PR TITLE
Feature/map pie

### PR DESCRIPTION
**Pull request by eirikcsak**

### CODE REVIEW

**Comment by eirikcsak** [comment]
@runarbe: pushed anchor layout as discussed to the PR

**Comment by eirikcsak** [comment]
@runarbe: pushed map and vizlayer changes as disscussed

**Comment by eirikcsak** [comment]
@runarbe: moved position of vizObjects to layout and map layer. Use CSS for anchor layout. Please review asap.

**Comment by runarbe** [comment]
@eirikcsak reviewed and merged - no code critique beyond what has been discussed previously...

**Pull request merged**
